### ISSUE TITLE
Emty jar for 2.0.0 in maven repository

### ISSUE THREAD

**Issue by nnegativ** [allegro/embedded-elasticsearch#10]
Archive available here: http://central.maven.org/maven2/pl/allegro/tech/embedded-elasticsearch/2.0.0/ contains only manifest file.

**Comment by gaczm** [comment]
Thanks for your watchful eye! Empty jar is a result of changes in gradle submodules. I've just released 2.0.1 with valid jar. Unfortunately I cannot do anything with 2.0.0, so it have to stay as is in maven central
