### ISSUE TITLE
"Failed to start elasticsearch within time-out" when running within Jenkins

### ISSUE THREAD

**Issue by Habitats** [allegro/embedded-elasticsearch#14]
I'm have a pretty simple build that starts up an embedded instance, which works fine both through IDEA and gradle CLI. However, when I run the job in Jenkins, I get this error when starting the embedded server:

```
pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Failed to start elasticsearch within time-out
```

I've spoken with the Jenkins folks, and they see no reason this should not work. I therefore wonder if this is a bug, or some other known issue, or if there are some recommended way to use embedded-elasticsearch with Jenkins.

The code I'm running is simply 

```scala
val client = EmbeddedElastic.builder()
      .withElasticVersion("2.3.1")
      .withSetting(PopularProperties.TRANSPORT_TCP_PORT, 9300)
      .withSetting(PopularProperties.CLUSTER_NAME, "elastic-test")
      .withSetting("http.cors.allow-origin", "*")
      .withSetting("http.cors.enabled", true)
      .withIndex("foo", IndexSettings.builder()
        .withType("bar", "template.json")
        .build())
      .build()
  
client.start() // this crashes
```

Other

- ES version: 2.3.1
- Scala: 2.11.8
- Java: 1.8_101
- Jenkins: 2.33
- OS: Debian 8

**Comment by gaczm** [comment]
Hi, 
First thing: try increasing timeout (method `withStartTimeout` on builder). It defaults to 15 secs which is quite a lot, but maybe workers used by your Jenkins are so slow/overloaded that it's not enough for them. BTW I had to do such thing in embedded-elasticsearch tests: https://github.com/allegro/embedded-elasticsearch/blob/master/es50-test/src/test/groovy/pl/allegro/tech/embeddedelasticsearch/EmbeddedElasticSpec.groovy because travis had timeouts

**Comment by gaczm** [comment]
@Habitats does that solved your problem?

**Comment by Habitats** [comment]
Sorry, I ended up just setting up a persistent local server on my Jenkins server. I totally forgot about this issue. As this is no longer a real issue for me, you can just close it if you want.

**Comment by silvestrelosada** [comment]
I have the same problem, I'm increasing the timeout but it is launching the error. 

What I noticed is If I launch the application from unit test it breaks, Im using it in the application and seems to work fine.

**Comment by kimberly-eis** [comment]
I am also having this issue. :/

**Comment by kimberly-eis** [comment]
Resolved this issue by expanding the heap memory for the slave.  It required more memory than jenkins was providing.

**Comment by rdooley-sc** [comment]
I am having this problem.... my tests wont run on jenkins using embedded-elasticsearch library. I am just getting the generic exception - EmbeddedElasticsearchStartupException

Kimberly-els - how do you change the heap memory for slave? Is it a Jenkins configuration option?

**Comment by kimberly-eis** [comment]
I didn't personally expand it, it was done by the part of my company that runs the jenkins server.

**Comment by kimberly-eis** [comment]
@rdooley-sc Make sure that your embedded elastic is getting torn down each time too, if you leave it running, another copy will not be able to start up.

**Comment by rdooley-sc** [comment]
Thanks
