### ISSUE TITLE
Project maven repository

### ISSUE THREAD

**Issue by dangxunb** [allegro/embedded-elasticsearch#2]
Hello, thanks for writing this great project. But I can not found the maven repository. Can you give me one?

**Comment by dangxunb** [comment]
I've found it at this article:
[http://allegro.tech/2016/09/embedded-elasticsearch.html](Allegro OpenSource — embedded-elasticsearch)

It's great if someone can put it in README.md 👍

**Comment by gaczm** [comment]
Hi, thank you for your interest in project. I've added section about adding embedded-elastic as dependency to README file as you suggested
