### ISSUE TITLE
Unable to install plugin: analysis-stempel

### ISSUE THREAD

**Issue by jobetdelima** [allegro/embedded-elasticsearch#27]
Hi,

I'm trying to use your lib in my scala SBT project.

I have a TestHelper set-up like below. It has methods that can then be used in beforeAll and afterAll in my TestRunner.

import pl.allegro.tech.embeddedelasticsearch.{EmbeddedElastic, PopularProperties}

/**
  * TestHelper Singleton for local ES node
  */
object TestHelper {
  val embeddedElastic: EmbeddedElastic = EmbeddedElastic.builder()
    .withElasticVersion("5.3.0")
    .withSetting(PopularProperties.TRANSPORT_TCP_PORT, 9350)
    .withSetting(PopularProperties.CLUSTER_NAME, "local")
    .withEsJavaOpts("-Xms128m -Xmx512m")
    .withPlugin("analysis-stempel")
    .build()
    .start()

  def prepareLocalNode(): Unit = {
    embeddedElastic.start()
  }

  def cleanLocalNode(): Unit = {
    embeddedElastic.stop()
  }

}

Running the TestRunner results in the following:
$ sbt test
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from blah-blah/.sbt/0.13/plugins
[info] Loading project definition from blah-blah
[info] Set current project to geolocation-api (in build file:blah-blah)
[info] Compiling 1 Scala source to blah-blah...
[info] Compiling 1 Scala source to blah-blah...
Before All: Prepare Test ES local node
[INFO] date=2017-09-22 17:58:09,871 message=Download skipped
[INFO] date=2017-09-22 17:58:09,873 message=Installing Elasticsearch into /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir...
[INFO] date=2017-09-22 17:58:10,147 message=Done
[INFO] date=2017-09-22 17:58:10,199 message=Applying executable permissions on /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/bin/elasticsearch-plugin
[INFO] date=2017-09-22 17:58:10,200 message=> /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/bin/elasticsearch-plugin install analysis-stempel
-> Downloading analysis-stempel from elastic
[=================================================] 100%  
-> Installed analysis-stempel
[INFO] date=2017-09-22 17:58:12,039 message=Applying executable permissions on /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/bin/elasticsearch
[INFO] date=2017-09-22 17:58:12,042 message=Applying executable permissions on /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/bin/elasticsearch.in.sh
[INFO] date=2017-09-22 17:58:12,071 message=Waiting for ElasticSearch to start...
[INFO] date=2017-09-22 17:58:12,928 message=[2017-09-22T17:58:12,927][INFO ][o.e.n.Node               ] [] initializing ...
[INFO] date=2017-09-22 17:58:12,985 message=[2017-09-22T17:58:12,985][INFO ][o.e.e.NodeEnvironment    ] [PYyODht] using [1] data paths, mounts [[/ (/dev/disk1)]], net usable_space [364.7gb], net total_space [464.7gb], spins? [unknown], types [hfs]
[INFO] date=2017-09-22 17:58:12,986 message=[2017-09-22T17:58:12,985][INFO ][o.e.e.NodeEnvironment    ] [PYyODht] heap size [494.9mb], compressed ordinary object pointers [true]
[INFO] date=2017-09-22 17:58:12,987 message=[2017-09-22T17:58:12,986][INFO ][o.e.n.Node               ] node name [PYyODht] derived from node ID [PYyODhthRYS5T_LP1kv_5g]; set [node.name] to override
[INFO] date=2017-09-22 17:58:12,987 message=[2017-09-22T17:58:12,987][INFO ][o.e.n.Node               ] version[5.3.0], pid[50769], build[3adb13b/2017-03-23T03:31:50.652Z], OS[Mac OS X/10.11.6/x86_64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_102/25.102-b14]
[INFO] date=2017-09-22 17:58:12,989 message=Detected Elasticsearch PID : 50769
[INFO] date=2017-09-22 17:58:13,578 message=[2017-09-22T17:58:13,578][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [aggs-matrix-stats]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,578][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [ingest-common]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [lang-expression]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [lang-groovy]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [lang-mustache]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [lang-painless]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [percolator]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [reindex]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [transport-netty3]
[INFO] date=2017-09-22 17:58:13,579 message=[2017-09-22T17:58:13,579][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded module [transport-netty4]
[INFO] date=2017-09-22 17:58:13,580 message=[2017-09-22T17:58:13,580][INFO ][o.e.p.PluginsService     ] [PYyODht] loaded plugin [analysis-stempel]
[INFO] date=2017-09-22 17:58:14,793 message=[2017-09-22T17:58:14,793][INFO ][o.e.n.Node               ] initialized
[INFO] date=2017-09-22 17:58:14,793 message=[2017-09-22T17:58:14,793][INFO ][o.e.n.Node               ] [PYyODht] starting ...
[INFO] date=2017-09-22 17:58:14,917 message=[2017-09-22T17:58:14,917][INFO ][o.e.t.TransportService   ] [PYyODht] publish_address {127.0.0.1:9350}, bound_addresses {[fe80::1]:9350}, {[::1]:9350}, {127.0.0.1:9350}
[INFO] date=2017-09-22 17:58:14,917 message=Detected Elasticsearch transport tcp port : 9350
[INFO] date=2017-09-22 17:58:14,921 message=[2017-09-22T17:58:14,921][WARN ][o.e.b.BootstrapChecks    ] [PYyODht] initial heap size [134217728] not equal to maximum heap size [536870912]; this can cause resize pauses and prevents mlockall from locking the entire heap
[INFO] date=2017-09-22 17:58:17,958 message=[2017-09-22T17:58:17,958][INFO ][o.e.c.s.ClusterService   ] [PYyODht] new_master {PYyODht}{PYyODhthRYS5T_LP1kv_5g}{9tOdjKPQQtCdFaU-HL6kqg}{127.0.0.1}{127.0.0.1:9350}, reason: zen-disco-elected-as-master ([0] nodes joined)
[INFO] date=2017-09-22 17:58:17,973 message=[2017-09-22T17:58:17,973][INFO ][o.e.h.n.Netty4HttpServerTransport] [PYyODht] publish_address {127.0.0.1:9200}, bound_addresses {[fe80::1]:9200}, {[::1]:9200}, {127.0.0.1:9200}
[INFO] date=2017-09-22 17:58:17,974 message=Detected Elasticsearch http port : 9200
[INFO] date=2017-09-22 17:58:17,975 message=[2017-09-22T17:58:17,975][INFO ][o.e.n.Node               ] [PYyODht] started
[INFO] date=2017-09-22 17:58:17,975 message=ElasticSearch started...
[INFO] date=2017-09-22 17:58:17,978 message=[2017-09-22T17:58:17,978][INFO ][o.e.g.GatewayService     ] [PYyODht] recovered [0] indices into cluster_state
[INFO] date=2017-09-22 17:58:18,142 message=Download skipped
[INFO] date=2017-09-22 17:58:18,142 message=Installing Elasticsearch into /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir...
[INFO] date=2017-09-22 17:58:18,410 message=Done
[INFO] date=2017-09-22 17:58:18,411 message=Applying executable permissions on /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/bin/elasticsearch-plugin
[INFO] date=2017-09-22 17:58:18,411 message=> /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/bin/elasticsearch-plugin install analysis-stempel
-> Downloading analysis-stempel from elastic
[=================================================] 100%  
ERROR: plugin directory [/var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir/elasticsearch-5.3.0/plugins/analysis-stempel] already exists; if you need to update the plugin, uninstall it first using command 'remove analysis-stempel'
After All: Delete test index
[INFO] date=2017-09-22 17:58:19,807 message=Stopping elasticsearch server...
[INFO] date=2017-09-22 17:58:19,817 message=[2017-09-22T17:58:19,814][INFO ][o.e.n.Node               ] [PYyODht] stopping ...
[INFO] date=2017-09-22 17:58:19,833 message=[2017-09-22T17:58:19,833][INFO ][o.e.n.Node               ] [PYyODht] stopped
[INFO] date=2017-09-22 17:58:19,833 message=[2017-09-22T17:58:19,833][INFO ][o.e.n.Node               ] [PYyODht] closing ...
[INFO] date=2017-09-22 17:58:19,840 message=[2017-09-22T17:58:19,840][INFO ][o.e.n.Node               ] [PYyODht] closed
[INFO] date=2017-09-22 17:58:19,882 message=Elasticsearch exited with RC 130
[INFO] date=2017-09-22 17:58:19,882 message=Removing installation directory...
[INFO] date=2017-09-22 17:58:19,904 message=Finishing...
[info] TestRunner:
[info] TestRunner *** ABORTED ***
[info]   pl.allegro.tech.embeddedelasticsearch.EmbeddedElasticsearchStartupException: Unable to install plugin: analysis-stempel
[info]   at pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller.installPlugins(ElasticSearchInstaller.java:80)
[info]   at pl.allegro.tech.embeddedelasticsearch.ElasticSearchInstaller.install(ElasticSearchInstaller.java:50)
[info]   at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.installElastic(EmbeddedElastic.java:56)
[info]   at pl.allegro.tech.embeddedelasticsearch.EmbeddedElastic.start(EmbeddedElastic.java:47)
[info]   at TestHelper$.prepareLocalNode(TestHelper.scala:40)
[info]   at TestRunner.beforeAll(TestRunner.scala:19)
[info]   at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:212)
[info]   at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
[info]   at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
[info]   at TestRunner.run(TestRunner.scala:12)
[info]   ...
[info] Run completed in 10 seconds, 476 milliseconds.
[info] Total number of tests run: 0
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 0, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[error] Error during tests:
[error] 	TestRunner
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 14 s, completed 22-Sep-2017 5:58:19 PM
[INFO] date=2017-09-22 17:58:19,976 message=Stopping elasticsearch server...
[INFO] date=2017-09-22 17:58:19,976 message=Removing installation directory...
[INFO] date=2017-09-22 17:58:19,977 message=Finishing...

Any lead would be appreciated!

**Comment by gaczm** [comment]
Hi, it seems that you are starting embedded elasticsearch twice. Look at those logs:

```
[INFO] date=2017-09-22 17:58:17,975 message=ElasticSearch started...
```

and then you got: 

```
[INFO] date=2017-09-22 17:58:18,142 message=Download skipped
[INFO] date=2017-09-22 17:58:18,142 message=Installing Elasticsearch into /var/folders/9s/jn7xwkf150x_147t7bp1tgd5vw1_3j/T/embedded-elasticsearch-temp-dir...
```
Looking at your code snippet: you are invoking `start()` method in field declaration:

```
val embeddedElastic: EmbeddedElastic = EmbeddedElastic.builder()
.withElasticVersion("5.3.0")
.withSetting(PopularProperties.TRANSPORT_TCP_PORT, 9350)
.withSetting(PopularProperties.CLUSTER_NAME, "local")
.withEsJavaOpts("-Xms128m -Xmx512m")
.withPlugin("analysis-stempel")
.build()
.start()
```

and then in `prepareLocalNode` method:

```
def prepareLocalNode(): Unit = {
   embeddedElastic.start()
}
```

Get rid of one of those invocations and it will work :)

**Comment by jobetdelima** [comment]
Indeed, it worked after doing that! Woohoo. Thanks! Closing this "issue".
