### ISSUE TITLE
if plugin already exists in directory, startup fails

### ISSUE THREAD

**Issue by ItamarBenjamin** [allegro/embedded-elasticsearch#41]
I think the plugin should check if the plugin is installed before trying to install the plugin, sometimes tests fail without properly bringing elastic down and the folder remains on the system. then future tests fail because of this error.

Thank you!

**Comment by gaczm** [comment]
Hi, idea is to delete directory to remove all state, so whole directory have to be deleted. But I will add deleting directory before test starts. It should also help with this problem
