### ISSUE TITLE
Add possibility to run under different user

### ISSUE THREAD

**Issue by AndrewPonyk** [allegro/embedded-elasticsearch#45]
I faced the issue with Jenkins:

Jenkins runs build under root user, but Elasticsearch cannot be run with root user. Would be nice to config under which user Elasticsearch is started.

For example:

 EmbeddedElastic.builder()
                    .withElasticVersion("6.0.0")
                    .withInstallationDirectory(elasticsearchInstallationDir)
                    ....
                    .withSetting(PopularProperties.USER, "jenkins")
                    ....
                    .build()
                    .start();

**Comment by gridcellcoder** [comment]
Having the same issue on gitlab, did you manage to find a solution? I tried 
``` 
 .withSetting("ES_USER", "elasticsearch")
 .withSetting("ES_GROUP", "elasticsearch")
```

with no luck

**Comment by gaczm** [comment]
Hi, is there parameter for that in elasticsearch? If yes we can add this to embedded-elasticsearch. Otherwise I would recommend changing CI configuration to run as regular user :)

**Comment by AndrewPonyk** [comment]
@gaczm , there is not parameter/possibility in Elasticsearch for this.

Sometimes we can use CI with a regular user, but in some teams, there is no such possibility.
Thats why, we switched to docker containers instead of embedded-elasticsearch.

**Comment by gridcellcoder** [comment]
You are correct it wasn't an option ..though managed to run it as `su elasticsearch -c "command"` in our gitlab runner. `command` is a `mvn test` or launch of elasticsearch. This is a great tool btw helps save costs on having a continuously running cluster!

**Comment by gaczm** [comment]
@AndrewPonyk in linux yes, but linux is not the only supported platform :) Running tests as root doesn't sounds good and this is the only case where you would need such feature, so I don't see this as serious problem. But of course you can submit PR with such code
