### ISSUE TITLE
Parameters not taken in place  .withEsJavaOpts("-Xms128m -Xmx512m")

### ISSUE THREAD

**Issue by igieon** [allegro/embedded-elasticsearch#46]
Parameters are taken but not applied because :

From elasticsearch startup script (version 6.1.2)

>  Optionally, exact memory values can be set using the `ES_JAVA_OPTS`. Note that
>  the Xms and Xmx lines in the JVM options file must be commented out. Example
>  values are "512m", and "10g".

**Comment by gaczm** [comment]
Hi. This comment says exactly that if you want to change memory options you have to set ES_JAVA_OPTS variable and this is done by embedded-elasticsearch. And as far as I can see this option is applied to created elastic search instance. Do you have problems with this setting? If so, can you show me some example?

Thanks

**Comment by daveyx** [comment]
i have similar thing, i run:
`EmbeddedElastic.builder().withElasticVersion("5.6.5").withEsJavaOpts("-Xms512m -Xmx512m")`

but in the process list i can see:
`
 /usr/lib/jvm/java-8-oracle/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+AlwaysPreTouch -server -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Djdk.io.permissionsUseCanonicalPath=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Xms512m -Xmx512m -Des.path.home=/tmp/embedded-elasticsearch-temp-dir/elasticsearch-5.6.5 -cp /tmp/embedded-elasticsearch-temp-dir/elasticsearch-5.6.5/lib/* org.elasticsearch.bootstrap.Elasticsearch
`

so there are 2 definitions: -Xms2g -Xmx2g AND -Xms512m -Xmx512m
obviously the second definition is set, as i can see in the processtable that the process is NOT running with 2gb anymore

@igieon please note that elasticsearch wants you to set Xms and Xmx to the same value (at least for 5.6.x)

**Comment by gaczm** [comment]
I'm closing this issue. As @daveyx said: xms and xmx are set second time by embedded elasticsearch  and that setting is used, which is ok (first setting is a default from elasticsearch init files).
