### ISSUE TITLE
jdk10 not supported

### ISSUE THREAD

**Issue by gut9** [allegro/embedded-elasticsearch#65]
Can not run ES with jdk10.  There is some problem with file permission. Tested locally with jdk10, on the docker with linux and jdk10 and with another project using lib embedded-elasticsearch. Always the same issues.

**Comment by gut9** [comment]
I'm running on macOs. Bug was resolved in [https://bugs.openjdk.java.net/browse/JDK-8075110] but lib jarchivelib has no compatibility with jdk9/10.

**Comment by evanpaschke** [comment]
Should be fixed with: https://github.com/thrau/jarchivelib/pull/72
